[gui]
window_title = "Todo App"

[shortcuts]
new_todo = "Ctrl+N"
delete_todo = "Ctrl+D"

# Warnings
[warning.content_too_short]
title = ""
text = ""

[warning.no_selection]
title = ""
text = ""

# Dialogs
[dialog.insert_todo]
title = ""
placeholder = ""

[icons]
window_icon = ""
