[gui]
window_title = "Todo App"

[shortcuts]
new_todo = "Ctrl+N"
delete_todo = "Ctrl+D"

# Warnings
[warning.content_too_short]
title = "Content is too short"
text = "Your content must be at least 5 characters long."

[warning.no_selection]
title = "No selection"
text = "You have not selected any row."

# Dialogs
[dialog.insert_todo]
title = "Create New Todo"
placeholder = "Content"

[icons]
window_icon = ""
